Fixed: import third-party packages after updating library path
ThreatConnect-Inc/tcex-app-templates pull request #43
Opened 2023-05-22 17:25 UTC by quinnzipse

Import this tcex package after the library paths are updated so it can properly find the package.

Fixed this error when running the custom app based on this template:

```
Traceback (most recent call last):
  File "/opt/python3.6.15/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python3.6.15/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 3, in <module>
    from run import run
  File "./run.py", line 8, in <module>
    from tcex.app_config.install_json import InstallJson
ModuleNotFoundError: No module named 'tcex.app_config'
```

2023-05-23 15:39 UTC, cblades-tc approved these changes

2023-05-23 15:48 UTC, cblades-tc requested changes
Thank you for finding this and submitting a PR!  

Could you please add
# isort: off
on line 19 (before the two tcex imports)

and # isort: on line 26 (after the app import).

Else the changes fail linting.

Thank you!

2023-05-24 16:51 UTC, quinnzipse commented
Hi, thank you for the feedback. I switched the order of imports. 

When running isort locally, it resolved the issue. It also passed the test on Github.

Reach out if you need me to make any other modifications!

2023-05-24 18:20 UTC, cblades-tc approved these changes

2023-05-24 18:20 UTC, cblades-tc commented
Thanks again!

2023-05-24 18:20 UTC, merged